name: tiago_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pyaudio
  - tensorflow=2.11.0
  - numpy<2.0
  - opencv
  - pandas
  - matplotlib
  - scipy
  - pillow
  - pip:
      - transformers
      - sentencepiece
      - gtts
      - flask
      - openai-whisper
      - deepface
      - ultralytics
      - supervision


# add: conda tk 


# To create this env with conda:
# conda env create -f src/config/tiago_env.yaml

# To update in case requirements changed:
# conda env update --name tiago_env --file src/config/tiago_env.yaml --prune

# To remove the env instead (if you want a clean rebuild for example):
# conda remove --name tiago_env --all

# To generate requirements.txt file for pip (useful for venv or pip install):
# pip freeze > src/config/tiago_requirements.txt